services:
  api-service:
    container_name: api-container
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '9000:8080'
    networks:
      - backend

  redis:
    image: redis:6.2-alpine
    container_name: redis-container
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - backend

networks:
  backend:
    driver: bridge