spring:
  config:
    activate:
      on-profile: test
open:
  api:
    title: ${API_TITLE :DUMMY_API_TITLE_TEST}
    version: 1.0.0
    description: API document for java-practice-code
    serverUrl: http://localhost:${server.port}
    serverName: localhost